from rest_framework import serializers


class RandomUserSerializer(serializers.Serializer):
    gender = serializers.CharField(max_length=10)
    title = serializers.CharField(max_length=10)
    first_name = serializers.CharField(max_length=50)
    last_name = serializers.CharField(max_length=50)
    street_number = serializers.IntegerField()
    street_name = serializers.CharField(max_length=100)
    city = serializers.CharField(max_length=50)
    state = serializers.CharField(max_length=50)
    country = serializers.CharField(max_length=50)
    postcode = serializers.CharField(max_length=20)
    latitude = serializers.CharField(max_length=20)
    longitude = serializers.CharField(max_length=20)
    timezone_offset = serializers.CharField(max_length=10)
    timezone_description = serializers.CharField(max_length=100)
    email = serializers.EmailField()
    username = serializers.CharField(max_length=50)
    password = serializers.CharField(max_length=100)
    dob = serializers.DateField()
    age = serializers.IntegerField()
    phone = serializers.CharField(max_length=20)
    cell = serializers.CharField(max_length=20)
    picture_large = serializers.URLField()
    picture_medium = serializers.URLField()
    picture_thumbnail = serializers.URLField()
    nat = serializers.CharField(max_length=5)
